apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-test
  namespace: demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::513312840319:role/DIL_TEST_S3_READ-ONLY