apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "1500Mi"
      requests:
        memory: "1000Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "1250M", "--vm-hang", "180"]
